target("platform")
    set_kind("binary")
    add_headerfiles("./*.h")
    add_files("./*.cpp")
    add_packages("eigen", "boost", "glfw", "vulkan-hpp", "vulkan-memory-allocator-hpp", "spirv-reflect", "fmt", "zlib")
    add_deps("common", "driver", "engine")
    add_links("common", "driver", "engine")
    add_linkdirs("$(buildir)/$(plat)/$(arch)/$(mode)/common/", "$(buildir)/$(plat)/$(arch)/$(mode)/driver/", "$(buildir)/$(plat)/$(arch)/$(mode)/engine/") 
    add_includedirs("$(projectdir)/common/", "$(projectdir)/driver/", "$(projectdir)/engine/") 