target("driver")
    set_kind("static")
    add_headerfiles("./**/*.h")
    add_files("./**/*.cpp")
    add_packages("eigen", "vulkan-hpp", "vulkan-memory-allocator-hpp", "spirv-reflect", "fmt")
    add_deps("common")
    add_linkdirs(os.getenv("VK_SDK_PATH").."/Lib/")
    add_links("vulkan-1")
    add_defines("GUNGNIR_STATIC")